#!/usr/bin/env python3
"""
Script to generate bimanual panda with tesollo gripper URDF from single-arm URDF.

This script reads the single-arm panda_w_tesollo.urdf and creates a bimanual version
by duplicating the arm with different prefixes and mounting positions.

Usage:
    python generate_bimanual_panda_tesollo.py
"""

import xml.etree.ElementTree as ET
from pathlib import Path


def add_prefix_to_element(element, prefix, tag_name):
    """Add prefix to element attributes that reference links/joints."""
    attrs_to_prefix = {
        'joint': ['name'],
        'link': ['name'],
        'parent': ['link'],
        'child': ['link'],
        'material': ['name']
    }

    if element.tag in attrs_to_prefix:
        for attr in attrs_to_prefix[element.tag]:
            if attr in element.attrib:
                # Don't prefix material colors that are standard
                if element.tag == 'material' and element.attrib[attr] in ['black', 'white']:
                    element.attrib[attr] = f"{prefix}{element.attrib[attr]}"
                elif element.tag != 'material':
                    element.attrib[attr] = f"{prefix}{element.attrib[attr]}"


def add_prefix_to_tree(root, prefix):
    """Recursively add prefix to all relevant elements in the tree."""
    for element in root.iter():
        add_prefix_to_element(element, prefix, element.tag)

        # Update mesh filenames to use relative paths
        if element.tag == 'mesh' and 'filename' in element.attrib:
            filename = element.attrib['filename']
            # Convert from absolute to relative path
            if filename.startswith('../'):
                element.attrib['filename'] = filename
            elif not filename.startswith('package://'):
                # Keep relative paths as-is
                pass


def add_table_top(bimanual_root,
                  dims=(1.8288, 0.62865, 0.045),
                  color_rgba="0.70 0.50 0.30 1.0"):
    """
    Add a table_top link and its fixed joint to world.

    The table surface is at z=0 (world origin).  The box is therefore centred at
    z = -dims[2]/2 so that its top face is flush with z=0.

    Args:
        bimanual_root : root Element to append to
        dims          : (length_x, width_y, thickness_z) in metres
        color_rgba    : RGBA colour string for the visual material
    """
    lx, ly, lz = dims
    center_z = -lz / 2.0          # top face at z=0  →  centre at z=-lz/2

    # --- link -----------------------------------------------------------------
    table_link = ET.SubElement(bimanual_root, 'link', name='table_top')

    visual = ET.SubElement(table_link, 'visual')
    ET.SubElement(visual, 'origin', xyz="0 0 0", rpy="0 0 0")
    vis_geom = ET.SubElement(visual, 'geometry')
    ET.SubElement(vis_geom, 'box', size=f"{lx} {ly} {lz}")
    vis_mat = ET.SubElement(visual, 'material', name='wood')
    ET.SubElement(vis_mat, 'color', rgba=color_rgba)

    collision = ET.SubElement(table_link, 'collision')
    ET.SubElement(collision, 'origin', xyz="0 0 0", rpy="0 0 0")
    col_geom = ET.SubElement(collision, 'geometry')
    ET.SubElement(col_geom, 'box', size=f"{lx} {ly} {lz}")

    # --- joint ----------------------------------------------------------------
    joint = ET.SubElement(bimanual_root, 'joint',
                          name='table_top_joint', type='fixed')
    ET.SubElement(joint, 'parent', link='world')
    ET.SubElement(joint, 'child', link='table_top')
    ET.SubElement(joint, 'origin',
                  xyz=f"0 0 {center_z:.6f}",
                  rpy="0 0 0")


def create_bimanual_urdf(single_arm_urdf_path, output_path,
                         left_position=(-0.558, -0.092, 0.0225),
                         right_position=(0.5588, -0.092, 0.0225)):
    """
    Create a bimanual URDF from a single-arm URDF.

    Args:
        single_arm_urdf_path: Path to the single-arm URDF file
        output_path: Path where the bimanual URDF will be saved
        left_position: (x, y, z) position of left arm base relative to world
        right_position: (x, y, z) position of right arm base relative to world
    """
    # Parse the single-arm URDF
    tree = ET.parse(single_arm_urdf_path)
    root = tree.getroot()

    # Create new root for bimanual robot
    bimanual_root = ET.Element('robot', name='bimanual_panda_tesollo')

    # Add XML declaration comment
    comment_text = """
==================================================================================
This URDF was generated by generate_bimanual_panda_tesollo.py
Do not edit this file directly. Instead, modify the generator script.
==================================================================================
"""
    bimanual_root.append(ET.Comment(comment_text))

    # Create world/base link
    world_link = ET.SubElement(bimanual_root, 'link', name='world')

    # Process left arm
    print("Processing left arm...")
    left_tree = ET.parse(single_arm_urdf_path)
    left_root = left_tree.getroot()
    add_prefix_to_tree(left_root, 'left_')

    # Add all links and joints from left arm
    for child in left_root:
        if child.tag in ['link', 'joint', 'material']:
            bimanual_root.append(child)

    # Process right arm
    print("Processing right arm...")
    right_tree = ET.parse(single_arm_urdf_path)
    right_root = right_tree.getroot()
    add_prefix_to_tree(right_root, 'right_')

    # Add all links and joints from right arm
    for child in right_root:
        if child.tag in ['link', 'joint', 'material']:
            bimanual_root.append(child)

    # Add table_top (surface at z=0, box extends downward)
    add_table_top(bimanual_root)

    # Create mounting joints for both arms
    # Left arm mount
    left_mount = ET.SubElement(bimanual_root, 'joint',
                               name='left_panda_mount',
                               type='fixed')
    left_parent = ET.SubElement(left_mount, 'parent', link='world')
    left_child = ET.SubElement(left_mount, 'child', link='left_panda_link0')
    left_origin = ET.SubElement(left_mount, 'origin',
                                xyz=f"{left_position[0]} {left_position[1]} {left_position[2]}",
                                rpy="0 0 0")

    # Right arm mount (rotated 180 degrees around z-axis)
    right_mount = ET.SubElement(bimanual_root, 'joint',
                                name='right_panda_mount',
                                type='fixed')
    right_parent = ET.SubElement(right_mount, 'parent', link='world')
    right_child = ET.SubElement(right_mount, 'child', link='right_panda_link0')
    right_origin = ET.SubElement(right_mount, 'origin',
                                 xyz=f"{right_position[0]} {right_position[1]} {right_position[2]}",
                                 rpy="0 0 3.14159265359")

    # Pretty print XML
    ET.indent(bimanual_root, space='  ')

    # Create the tree and write to file
    bimanual_tree = ET.ElementTree(bimanual_root)

    # Write with XML declaration
    with open(output_path, 'wb') as f:
        f.write(b'<?xml version="1.0" ?>\n')
        bimanual_tree.write(f, encoding='utf-8', xml_declaration=False)

    print(f"Bimanual URDF saved to: {output_path}")

    return output_path


def main():
    """Main function to generate the bimanual URDF."""
    # Get paths
    script_dir = Path(__file__).parent
    single_arm_urdf = script_dir.parent / 'rl' / 'panda_w_tesollo.urdf'
    output_urdf = script_dir.parent / 'rl' / 'bimanual_panda_tesollo.urdf'

    # Check if input file exists
    if not single_arm_urdf.exists():
        raise FileNotFoundError(f"Single-arm URDF not found at: {single_arm_urdf}")

    print(f"Reading single-arm URDF from: {single_arm_urdf}")
    print(f"Output will be saved to: {output_urdf}")

    # Create the bimanual URDF
    # Positions based on bimanual_arms.urdf.xacro
    # Left arm: xyz="-0.558 -0.092 0.0225" (facing forward)
    # Right arm: xyz="0.5588 -0.092 0.0225" (rotated 180° around z)
    create_bimanual_urdf(
        single_arm_urdf_path=single_arm_urdf,
        output_path=output_urdf,
        left_position=(-0.558, -0.092, 0.0), # z was 0.225
        right_position=(0.5588, -0.092, 0.0) # z was 0.225
    )

    print("\n✓ Bimanual URDF generation complete!")
    print(f"✓ Generated file: {output_urdf}")


if __name__ == '__main__':
    main()
